// Code generated by "stringer -trimprefix Color -type Color"; DO NOT EDIT.

package opshell

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorNone-0]
	_ = x[ColorBlack-1]
	_ = x[ColorRed-2]
	_ = x[ColorGreen-3]
	_ = x[ColorYellow-4]
	_ = x[ColorBlue-5]
	_ = x[ColorMagenta-6]
	_ = x[ColorCyan-7]
	_ = x[ColorWhite-8]
	_ = x[ColorReset-9]
}

const _Color_name = "NoneBlackRedGreenYellowBlueMagentaCyanWhiteReset"

var _Color_index = [...]uint8{0, 4, 9, 12, 17, 23, 27, 34, 38, 43, 48}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
