package tlog

/*
 * msg.go
 * UnJSON'd log message
 * By J. Stuart McMurray
 * Created 20251212
 * Last Modified 20260814
 */

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"testing"
)

// Group is analogous to the group created by [slog.Logger.WithGroup].
type Group = map[string]any

// M is a convenient way to start a new Msg.
var M = NewMsg()

// Msg is a log message in Go terms.  It can either be built up with [NewMsg]
// and its methods or be unmarshalled from a JSON object.
// Msgs methods which return a Msg return a deep copy of the Msg.
type Msg struct {
	msg
}

// msg is what Msg says it is, but with exported fields to make JSONing and
// unJSONing easier.
type msg struct {
	Root Group
	cur  Group
	Path []string /* Path from root to cur. */
}

// NewMsg is a convenience function which returns a new Msg, ready for use.
// [M] may be more convenient for many use-cases.
func NewMsg() Msg {
	m := make(Group)
	return Msg{
		msg: msg{
			Root: m,
			cur:  m,
			Path: []string{},
		},
	}
}

// NewMsgFromJSON decodes the JSON object in s to a Msg.
// Calls to With and WithGroup add to the outermost group.
// This is meant to unmarshal JSON generated by [slog.JSONHandler].
// For native Msg serialization, see [Msg.MarshalJSON] and [Msg.UnmarshalJSON].
func NewMsgFromJSON(s string) (Msg, error) {
	/* And decode right back to a Msg. */
	m := NewMsg()
	if err := json.Unmarshal([]byte(s), &m.Root); nil != err {
		return Msg{}, fmt.Errorf("JSON-decoding: %w", err)
	}
	m.cur = m.Root
	return m, nil
}

// With returns a clone of m with a new value added, similar to
// [slog.Logger.With].
// If the key already exists, its value is changed in the clone.
// The value must be able to be marshalled to JSON, otherwise With panics.
// Error values are stored as strings, for compatibility with
// [slog.JSONHandler.Handle].
func (m Msg) With(key string, value any) Msg {
	n := m.MustClone()
	/* Store error values as strings. */
	if err, ok := value.(error); ok {
		value = err.Error()
	}
	n.cur[key] = value
	return n
}

// WithGroup returns a clone of m which adds keys and values with With to a
// new group with the given name.
// If the name already exists as a key, it is replaced.
func (m Msg) WithGroup(name string) Msg {
	n := m.MustClone()
	g := make(Group)
	n.cur[name] = g
	n.cur = g
	n.Path = append(n.Path, name)
	return n
}

// Clone returns a deep copy of Msg.
// Under the hood, it marshals to and from JSON.
func (m Msg) Clone() (Msg, error) {
	n := NewMsg()

	/* JSON roundtrip. */
	b, err := m.MarshalJSON()
	if nil != err {
		return Msg{}, fmt.Errorf("marshalling: %w", err)
	}
	if err := n.UnmarshalJSON(b); nil != err {
		return Msg{}, fmt.Errorf("unmarshalling: %w", err)
	}

	return n, nil
}

// MustClone is like Clone, but panics on error.
func (m Msg) MustClone() Msg {
	n, err := m.Clone()
	if nil != err {
		panic(fmt.Errorf("Msg.MustClone: %w", err))
	}
	return n
}

// IsZero indicates if m is Msg{}.
func (m Msg) IsZero() bool {
	return nil == m.Root && nil == m.cur && nil == m.Path
}

// Equal indicates whether m and n encode to the same JSON via [Msg.String].
// If either m or n are unable to be encoded to json, Equal panics.
func (m Msg) Equal(n Msg) bool { return m.String() == n.String() }

// String returns the JSON form of m.
// It panics if m cannot be encoded to JSON.
// See [Msg.ToJSON] for more details.
func (m Msg) String() string {
	j, err := m.ToJSON()
	if nil != err {
		panic(fmt.Errorf("Msg.String: %w", err))
	}
	return j
}

// MarshalJSON returns the JSON form of m.  Note that this is not the same
// as the what [slog.JSONHandler] produces.
func (m Msg) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.msg)
}

// UnmarshalJSON updates m with the contents of the JSON object in b.  This
// should nearly always be called as NewMsg().UnmarshalJSON(...).
func (m *Msg) UnmarshalJSON(b []byte) error {
	/* Update m.msg. */
	var mm msg
	if err := json.Unmarshal(b, &mm); nil != err {
		return fmt.Errorf("JSON-decoding: %w", err)
	}
	mm.cur = mm.Root
	m.msg = mm

	/* update the current group. */
	for i, name := range m.Path {
		/* Down the rabbithole one level. */
		v, ok := m.cur[name]
		if !ok {
			return groupPathMissingError{Path: m.Path[:i+1]}
		}
		/* Make sure it's actually a group. */
		g, ok := v.(Group)
		if !ok {
			return newGroupPathLeadsToNotGroupError(
				m.Path[:i+1],
				v,
			)
		}
		m.cur = g
	}
	return nil
}

// ToJSON returns the JSON form of the log message in m, eliding empty groups.
// This is the inverse of NewMsgFromJSON and should return the same JSON object
// produced by [slog.JSONHandler], albeit possibly with a different key
// ordering.
func (m Msg) ToJSON() (string, error) {
	/* Copy with no empty groups. */
	n, err := m.Clone()
	if nil != err {
		return "", fmt.Errorf("cloning: %w", err)
	}
	removeEmptyGroups(n.Root)

	/* For testing, we'll look for a specific key in n.Root and replace
	its value with an unmarshallable number. */
	if testing.Testing() {
		if _, ok := n.Root[testUnmarshallableKey]; ok {
			n.Root[testUnmarshallableKey] = testUnmarshallableValue
		}
	}

	/* JSONify the important bit. */
	b, err := json.Marshal(n.Root)
	if nil != err { /* Unpossible */
		return "", fmt.Errorf("JSON-encoding: %w", err)
	}
	return string(b), nil
}

// Log returns a clone of m with a "level" ([slog.LevelKey]) attribute in the
// outermost group set to level and a "msg" ([slog.MessageKey]) attribute in
// the outermost group set to msg.  m is not modified.  Log panics on error.
func (m Msg) Log(level, msg string) Msg {
	n := m.MustClone()
	n.Root[slog.MessageKey] = msg
	n.Root[slog.LevelKey] = level
	return n
}

// Debug is a convenience method to Log at level [slog.Debug].
func (m Msg) Debug(msg string) Msg {
	return m.Log(slog.LevelDebug.String(), msg)
}

// Error is a convenience method to Log at level [slog.Error].
func (m Msg) Error(msg string) Msg {
	return m.Log(slog.LevelError.String(), msg)
}

// Info is a convenience method to Log at level [slog.Info].
func (m Msg) Info(msg string) Msg {
	return m.Log(slog.LevelInfo.String(), msg)
}

// Warn is a convenience method to Log at level [slog.Warn].
func (m Msg) Warn(msg string) Msg {
	return m.Log(slog.LevelWarn.String(), msg)
}

// removeEmptyGroups recursively removes empty groups from g.
func removeEmptyGroups(g Group) {
	for k, v := range g {
		/* Child group? */
		c, ok := v.(Group)
		if !ok { /* Don't care about non-groups. */
			continue
		}
		/* Remove empty child groups. */
		removeEmptyGroups(c)
		/* Remove this group if it's empty, which may have not been
		the case before recursion. */
		if 0 == len(c) {
			delete(g, k)
		}
	}
}

var (
	// testUnmarshallableKey is used to inject an unmarshallable value
	// into a Msg.
	testUnmarshallableKey = S("unmarshallable-key")
	// testUnmarshallableValue is the value injected when
	// testUnmarshallableKey is found in Msg.Root.
	testUnmarshallableValue = func() {}
)
