#!/usr/bin/env perl
#
# gen_other.pl
# Generate pledgeunveil_other.go
# By J. Stuart McMurray
# Created 20251010
# Last Modified 20251010

use autodie;
use strict;
use warnings;

use File::Basename;

# Work out the output file name.
die "Only one argument, please" unless 1 == 0+@ARGV;
my $ofn = $ARGV[0] =~ s/_openbsd/_other/r;
open my $fh, ">", $ofn;
select $fh;

# Note this is for !OpenBSD as well as it's been generated.
print "// Code generated by \"@{[basename($0)]} $ARGV[0]\"; DO NOT EDIT.\n";
print "\n";
print "//go:build !openbsd\n";
print "\n";

# Everything else is the same except the returns, which are always nil and the
# go:generate and import lines, which we skip.
while (<>) {
        next if /^\/\/go:generate/;
        next if /^import/;
        $_ = "$1return nil\n" if /^(\s+)return /;
        print;
}
