// Code generated by "gen_other.pl pledgeunveil_openbsd.go"; DO NOT EDIT.

//go:build !openbsd

// Package pledgeunveil - pledge(2) and unveil(2) on OpenBSD, no-ops elsewhere
package pledgeunveil

/*
 * pledgeunveil_openbsd.go
 * pledge(2) and unveil(2) on OpenBSD, no-ops elsewhere
 * By J. Stuart McMurray
 * Created 20251010
 * Last Modified 20251010
 */

// Pledge is a thin wrapper around [unix.Pledge]
// on OpenBSD and a no-op elsewhere.
func Pledge(promises, execpromises string) error {
	return nil
}

// PledgeExecpromises is a thin wrapper around [unix.PledgeExecpromises]
// on OpenBSD and a no-op elsewhere.
func PledgeExecpromises(execpromises string) error {
	return nil
}

// PledgePromises is a thin wrapper around [unix.PledgePromises]
// on OpenBSD and a no-op elsewhere.
func PledgePromises(promises string) error {
	return nil
}

// Unveil is a thin wrapper around [unix.Unveil]
// on OpenBSD and a no-op elsewhere.
func Unveil(path string, flags string) error {
	return nil
}

// UnveilBlock is a thin wrapper around [unix.UnveilBlock]
// on OpenBSD and a no-op elsewhere.
func UnveilBlock() error {
	return nil
}
