# t.subr
# Handy test subroutines and other things
# By J. Stuart McMurray
# Created 20250615
# Last Modified 20251025

set -euo pipefail

# current_git_branch prints the name of the current git branch to stdout.
function current_git_branch {
        set -e
        git rev-parse --abbrev-ref HEAD
}

# gorun runs with a safe(ish) listen address and no cert file
function gorun {
        go run . \
                -listen-address 127.0.0.1:0 \
                -no-timestamps \
                -tls-certificate-cache "" \
                "$@"
}

# vim: ft=sh
