#!/bin/ksh
#
# t.subr
# Handy test subroutines and other things
# By J. Stuart McMurray
# Created 20250615
# Last Modified 20260819

set -euo pipefail

# current_git_branch prints the name of the current git branch to stdout.
function current_git_branch {
        set -e
        git rev-parse --abbrev-ref HEAD
}

# gorun runs with a safe(ish) listen address and no cert file
function gorun {
        go run  . \
                -listen-address 127.0.0.1:0 \
                -no-timestamps \
                -tls-certificate-cache "" \
                "$@"
}

# gorun_pid is like gorun but causes curlrevshell's PID to be printed before
# execing curlrevshell.
function gorun_pid {
        go run -exec ./t/print_pid_and_exec.sh . \
                -listen-address 127.0.0.1:0 \
                -no-timestamps \
                -tls-certificate-cache "" \
                "$@"
}

# vim: ft=sh
