package hsrv

/*
 * script.go
 * HTTP handlers
 * By J. Stuart McMurray
 * Created 20240324
 * Last Modified 20241222
 */

import (
	_ "embed"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"math/rand"
	"net"
	"net/http"
	"strconv"
	"text/template"

	"github.com/magisterquis/curlrevshell/lib/crstemplate"
	"golang.org/x/net/idna"
)

// HTTPSPort is the default port for HTTPS and won't be added to URLs in
// generated scripts.
const HTTPSPort = "443"

// C2Param is a URL parameter or header which may be set in requetss to /c to
// give the URL to which to call back.
const C2Param = "c2"

// parseDefaultTemplate is the parsed form of DefaultTemplate.  We won't get
// very far if it doesn't parse.
var parsedDefaultTemplate = template.Must(
	template.New("").Parse(crstemplate.DefaultTemplate),
)

// scriptHandler serves up a script for calling us back.  Hope we like fork and
// exec...
func (s *Server) scriptHandler(w http.ResponseWriter, r *http.Request) {
	/* Generate template parameters. */
	c2, err := s.c2URL(r)
	if nil != err {
		s.RErrorLogf(r, "Could not determine callback URL: %s", err)
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	params := crstemplate.Params{
		PubkeyFP: s.l.Fingerprint,
		ID:       strconv.FormatUint(rand.Uint64(), 36),
		URL:      c2,
		URLPaths: s.ups,
	}

	/* Execute the template. */
	b, err := crstemplate.Execute(
		crstemplate.SubtemplateScript,
		s.tmplf,
		params,
	)
	if errors.Is(err, fs.ErrNotExist) {
		s.RErrorLogf(r, "Error reading template: %s", err)
	} else if nil != err {
		s.RErrorLogf(
			r,
			"Failed to execute %s template: %s",
			crstemplate.SubtemplateScript,
			err,
		)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	/* And send it back. */
	if _, err := io.WriteString(w, b); nil != err {
		s.RErrorLogf(r, "Error sending script: %s", err)
		return
	}
	s.RLogf(
		ScriptColor,
		r,
		"Sent script: ID:%s URL:%s",
		params.ID,
		params.URL,
	)
}

// c2URL tries to get a C2 URL from r.  We try a query/form parameter, a
// c2: header, the Host: header, and the SNI, in that order.
func (s *Server) c2URL(r *http.Request) (string, error) {
	/* Parse the query and form and try to get it from there. */
	if err := r.ParseForm(); nil != err {
		return "", fmt.Errorf("parsing request: %w", err)
	}
	if p := r.Form.Get(C2Param); "" != p {
		return p, nil
	}

	/* If it's not there, try to get it as a header. */
	if p := r.Header.Get(C2Param); "" != p {
		return p, nil
	}

	/* Failing that, try the Host: header. */
	if p, err := idna.ToASCII(r.Host); nil != err {
		return "", fmt.Errorf("punycoding %s: %w", r.Host, err)
	} else if "" != p {
		return p, nil
	}

	/* No Host: header.  Probably HTTP/1.0.  Try the SNI. */
	if p := r.TLS.ServerName; "" != p {
		/* Make sure to add the port if it's not the default.  This
		should be infrequent enough we can do it every time.  Famous
		last words. */
		_, lp, err := net.SplitHostPort(s.l.Addr().String())
		if nil != err {
			return "", fmt.Errorf("getting listen port: %w", err)
		}
		if lp != HTTPSPort {
			p = net.JoinHostPort(p, lp)
		}
		return p, nil
	}

	/* Out of ideas at this point. */
	return "", errors.New("out of ideas")
}

// printCallbackHelp prints a friendly message to the user with one-liners to
// get a callback.
func (s *Server) printCallbackHelp() {
	/* Get lines to print. */
	ls, err := s.lAddrLines(crstemplate.SubtemplateCallback)
	if nil != err {
		s.ErrorLogf("Error generating callback one-liners: %s", err)
		return
	}
	s.Logf(ScriptColor, "To get a shell:")
	for _, l := range ls {
		s.Printf(ScriptColor, "%s", l)
	}
}

// printStaticFileHelp prints a friendly message to the user with one-liners to
// get static files.
func (s *Server) printStaticFileHelp() {
	/* Get lines to print. */
	ls, err := s.lAddrLines(crstemplate.SubtemplateCallback)
	if nil != err {
		s.ErrorLogf(
			"Error generating static files one-liners: %s",
			err,
		)
		return
	}
	s.Logf(ScriptColor, "To get files from %s:", s.fdir)
	for _, l := range ls {
		s.Printf(ScriptColor, "%s", l)
	}
}

// lAddrLines returns a slice of strings generated by passing each element of
// s.lAddrs to the subtemplate named st, which should be one of the
// crstemplate.Subtemplate* constants.
// For convenience, the slice will start and end with strings containing a
// single newline each and the non-empty lines will be deduped.
func (s *Server) lAddrLines(st string) ([]string, error) {
	var (
		ret          = []string{"\n"}
		notedMissing bool
		seen         = make(map[string]struct{})
	)

	/* Roll a line for each address. */
	for _, la := range s.lAddrs {
		/* Roll a line. */
		l, err := crstemplate.Execute(st, s.tmplf, crstemplate.Params{
			PubkeyFP: s.l.Fingerprint,
			URL:      la,
			URLPaths: s.ups,
		})
		/* Note if we're missing the template. */
		if errors.Is(err, fs.ErrNotExist) {
			if !notedMissing {
				s.ErrorLogf(
					"Missing template file %s",
					s.tmplf,
				)
				notedMissing = true
			}
		} else if nil != err { /* Or other errors. */
			return nil, fmt.Errorf(
				"generating line for %s: %w",
				la,
				err,
			)
		}
		/* Dedupe generated lines. */
		if _, ok := seen[l]; ok {
			continue
		}
		seen[l] = struct{}{}

		ret = append(ret, l)
	}

	/* End with a blank line, for easy printing. */
	ret = append(ret, "\n")

	return ret, nil
}
