package hsrv

/*
 * script.go
 * HTTP handlers
 * By J. Stuart McMurray
 * Created 20240324
 * Last Modified 20250215
 */

import (
	_ "embed"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/magisterquis/curlrevshell/lib/crstemplate"
)

// noSubtemplateWarning is printed to the user to warn about a template file
// with template data but no subtemplates.
var noSubtemplateWarning = "\tYou probably need {{define \"" +
	crstemplate.SubtemplateCallback +
	"\"}} ... {{end}} around your template."

// scriptHandler serves up a script for calling us back.  Hope we like fork and
// exec...
func (s *Server) scriptHandler(w http.ResponseWriter, r *http.Request) {
	/* Generate template parameters. */
	params, err := crstemplate.AddRequest(s.params, r)
	if nil != err {
		s.RErrorLogf(
			r,
			"Error generating template parameters: %s",
			err,
		)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	/* Execute the template. */
	b, err := crstemplate.Execute(
		crstemplate.SubtemplateScript,
		s.tmplf,
		params,
	)
	if nil != err {
		s.RErrorLogf(
			r,
			"Failed to execute %s template: %s",
			crstemplate.SubtemplateScript,
			err,
		)
		s.maybeRecommendSubtemplate(err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	/* And send it back. */
	if _, err := io.WriteString(w, b); nil != err {
		s.RErrorLogf(r, "Error sending script: %s", err)
		return
	}
	s.RLogf(
		ScriptColor,
		r,
		"Sent script: ID:%s C2Addr:%s Path:%s",
		params.ID,
		params.C2Addr,
		params.Request.URL.Path,
	)
}

// printCallbackHelp prints a friendly message to the user with one-liners to
// get a callback.
func (s *Server) printCallbackHelp() {
	/* Get lines to print. */
	ls, err := s.lAddrLines(crstemplate.SubtemplateCallback)
	if nil != err {
		s.ErrorLogf("Error generating callback one-liners: %s", err)
		s.maybeRecommendSubtemplate(err)
		return
	}
	s.Logf(ScriptColor, "To get a shell:")
	for _, l := range ls {
		s.Printf(ScriptColor, "%s", l)
	}
}

// printStaticFileHelp prints a friendly message to the user with one-liners to
// get static files.
func (s *Server) printStaticFileHelp() {
	/* Get lines to print. */
	ls, err := s.lAddrLines(crstemplate.SubtemplateCallback)
	if nil != err {
		s.ErrorLogf(
			"Error generating static files one-liners: %s",
			err,
		)
		s.maybeRecommendSubtemplate(err)
		return
	}
	s.Logf(ScriptColor, "To get files from %s:", s.params.StaticFilesDir)
	for _, l := range ls {
		s.Printf(ScriptColor, "%s", l)
	}
}

// lAddrLines returns a slice of strings generated by passing each element of
// s.lAddrs to the subtemplate named st, which should be one of the
// crstemplate.Subtemplate* constants.
// For convenience, the slice will start and end with strings containing a
// single newline each and the non-empty lines will be deduped.
func (s *Server) lAddrLines(st crstemplate.SubtemplateName) ([]string, error) {
	var (
		ret    = []string{"\n"}
		seen   = make(map[string]struct{})
		params = s.params
	)

	/* Roll a line for each address. */
	for _, la := range s.lAddrs {
		/* Roll a line. */
		params.C2Addr = la
		l, err := crstemplate.Execute(st, s.tmplf, params)
		if nil != err {
			return nil, fmt.Errorf(
				"executing %s subtemplate for %s: %w",
				st,
				la,
				err,
			)
		}
		/* Dedupe generated lines. */
		if _, ok := seen[l]; ok {
			continue
		}
		seen[l] = struct{}{}

		ret = append(ret, l)
	}

	/* End with a blank line, for easy printing. */
	ret = append(ret, "\n")

	return ret, nil
}

// maybeRecommendSubtemplate recommends turning the template into a subtemplate
// if err is crstemplate.ErrOutsideSubtemplate.
func (s *Server) maybeRecommendSubtemplate(err error) {
	if errors.Is(err, crstemplate.ErrOutsideSubtemplate) ||
		errors.Is(err, crstemplate.ErrNoSubtemplates) {
		s.ErrorLogf("%s", noSubtemplateWarning)
	}
}
