package hsrv

/*
 * script.go
 * Callback script generator
 * By J. Stuart McMurray
 * Created 20240324
 * Last Modified 20260806
 */

import (
	_ "embed"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/magisterquis/curlrevshell/lib/crstemplate"
)

const (
	// callbackOneLinersName is the name intended for use when registering
	// callbackOneLiners with [iobroker.Broker.RegisterHelpMessage].
	callbackOneLinersName = "callback one-liners"

	// staticFilesOneLinersName is the name intended for use when
	// registering staticFilesOneLiners with
	// [iobroker.Broker.RegisterHelpMessage].
	staticFilesOneLinersName = "static files one-liners"
)

// noSubtemplateWarning is printed to the user to warn about a template file
// with template data but no subtemplates.
var noSubtemplateWarning = "\tYou probably need {{define \"" +
	crstemplate.SubtemplateCallback +
	"\"}} ... {{end}} around your template."

// RegisterOneLiners registers one-liner printing functions with s's iobroker.
func (s *Server) RegisterOneLiners() {
	if "" != s.params.StaticFilesDir {
		s.iob.RegisterHelpMessage(
			staticFilesOneLinersName,
			s.staticFilesOneLiners,
		)
	}
	s.iob.RegisterHelpMessage(
		callbackOneLinersName,
		s.callbackOneLiners,
	)
}

// scriptHandler serves up a script for calling us back.  Hope we like fork and
// exec...
func (s *Server) scriptHandler(w http.ResponseWriter, r *http.Request) {
	/* Generate template parameters. */
	params, err := crstemplate.AddRequest(s.params, r)
	if nil != err {
		s.rErrorLogf(
			r,
			"Error generating template parameters: %s",
			err,
		)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	/* Execute the template. */
	b, err := crstemplate.Execute(
		crstemplate.SubtemplateScript,
		s.tmplf,
		params,
	)
	if nil != err {
		s.rErrorLogf(
			r,
			"Failed to execute %s template: %s",
			crstemplate.SubtemplateScript,
			err,
		)
		if rec := s.maybeRecommendSubtemplate(err); "" != rec {
			s.errorLogf("%s", noSubtemplateWarning)
		}
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	/* Figure out how we're sending the result back. */
	iw := io.Writer(w)
	if ws := maybeWS(r.Context(), s.requestLogger(r), w, r); nil != ws {
		iw = ws
	}

	/* And send it back. */
	if _, err := io.WriteString(iw, b); nil != err {
		s.rErrorLogf(r, "Error sending script: %s", err)
		return
	}
	s.rLogf(
		scriptColor,
		r,
		"Sent script: ID:%s C2Addr:%s Path:%s",
		params.ID,
		params.C2Addr,
		params.Request.URL.Path,
	)
}

// CallbackOneLiners prints a friendly message to the user with one-liners to
// get a callback.
// It is meant to be registered with [iobroker.Broker.RegisterHelpMessage].
func (s *Server) callbackOneLiners() (string, error) {
	return s.addrLinesHelp(
		"To get a shell:",
		crstemplate.SubtemplateCallback,
	)
}

// staticFilesOneLiners prints a friendly message to the user with one-liners to
// get static files.
func (s *Server) staticFilesOneLiners() (string, error) {
	return s.addrLinesHelp(
		"To get files from "+s.params.StaticFilesDir+":",
		crstemplate.SubtemplateFiles,
	)
}

// addrLinesHelp returns help starting with hdr and then adds per-address lines
// generated with the given subtemplate.
func (s *Server) addrLinesHelp(
	hdr string,
	st crstemplate.SubtemplateName,
) (string, error) {
	/* Generate per-address bits. */
	ls, err := s.lAddrLines(st)
	if nil != err {
		if msg := s.maybeRecommendSubtemplate(err); "" != msg {
			err = fmt.Errorf("%w\n%s", err, msg)
		}
		return "", err
	}
	/* Roll it all together. */
	var sb strings.Builder
	sb.WriteString(hdr)
	sb.WriteRune('\n')
	sb.WriteRune('\n')
	for _, l := range ls {
		sb.WriteString(l)
		sb.WriteRune('\n')
	}

	return sb.String(), nil
}

// lAddrLines returns a slice of strings generated by passing each element of
// s.lAddrs to the subtemplate named st, which should be one of the
// crstemplate.Subtemplate* constants.
func (s *Server) lAddrLines(st crstemplate.SubtemplateName) ([]string, error) {
	var (
		seen   = make(map[string]struct{})
		params = s.params
		ret    []string
	)

	/* Roll a line for each address. */
	for _, la := range s.lAddrs {
		/* Roll a line. */
		params.C2Addr = la
		l, err := crstemplate.Execute(st, s.tmplf, params)
		if nil != err {
			return nil, fmt.Errorf(
				"executing %s subtemplate for %s: %w",
				st,
				la,
				err,
			)
		}
		/* Dedupe generated lines. */
		if _, ok := seen[l]; ok {
			continue
		}
		seen[l] = struct{}{}

		ret = append(ret, l)
	}

	return ret, nil
}

// maybeRecommendSubtemplate recommends turning the template into a subtemplate
// if err is crstemplate.ErrOutsideSubtemplate.
func (s *Server) maybeRecommendSubtemplate(err error) string {
	if errors.Is(err, crstemplate.ErrOutsideSubtemplate) ||
		errors.Is(err, crstemplate.ErrNoSubtemplates) {
		return noSubtemplateWarning
	}
	return ""
}
